require("lualine").setup({
	options = {
		icons_enabled = false,
		theme = "gruvbox_light",
		component_separators = " ",
		section_separators = "",
		disabled_filetypes = {},
		always_divide_middle = true,
		globalstatus = false,
	},
	sections = {
		lualine_a = { "filename" },
		lualine_b = {},
		lualine_c = {},
		-- lualine_x = { "diff", "diagnostics" },
		lualine_x = { "diagnostics" },
		lualine_y = { "progress" },
		lualine_z = { "location" },
	},
	inactive_sections = {
		lualine_a = { "filename" },
		lualine_b = {},
		lualine_c = {},
		lualine_x = {},
		lualine_y = {},
		lualine_z = { "location" },
	},
	tabline = {},
	extensions = {},
})
